
version: '3.1'

services:
  product-service:
    build:
      context: product-service\.
      args:
        JAR_FILE: ${JAR_FILE}
    image: rselva/product-service:beta
    environment:
      DB: db
    ports:
      - 8080:8080
    networks:
      - snet
      
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - model-data-volume:/data/db
      - model-config-volume:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hauX123
    networks:
      - snet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hauX123
    networks:
    - snet
    
volumes:
  model-data-volume:
  model-config-volume:
networks:
  snet: