
version: '3.1'

services:
  product-service:
    build:
      context: .
      args:
        JAR_FILE: ${JAR_FILE}
    image: rselva/product-service:beta
    environment:
      DB: db
    ports:
      - 8080:8080