server:
  port: 8080

spring:
  application:
    name: storeApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: modeldb
      authentication-database: admin
      username: root
      password: hauX123



# ribbon:
#   ServerListRefreshInterval: 1000

# endpoints:
#   health:
#     sensitive: false
#   restart:
#     enabled: true
#   shutdown:
#     enabled: true
